source 'https://rubygems.org'

gem 'rails', '~> 4.0.4'

gem 'aasm'
gem 'airbrake'
gem 'airbrake_user_attributes'
gem 'american_date'
gem 'activemerchant'
gem 'acts_as_list'
gem 'coffee-rails'#, '~> 3.2.1'
gem 'dalli'
gem 'dynamic_form'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'liquid'
gem 'mysql2'
gem 'newrelic_rpm', '>= 3.5.3.25'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-cas'
gem 'oa-openid'
gem 'paperclip'
gem 'rack-contrib'
gem 'sass-rails'#,   '~> 3.2.3'
gem 'sidekiq'
gem 'uglifier'#, '>= 1.0.3'

gem 'common_engine', 
  path: '/Users/andrewroth/Development/common_engine'
  # github: 'CruGlobal/common_engine', branch: 'master'
gem 'fe', 
  path: '/Users/andrewroth/Development/qe'
  # github: 'CruGlobal/qe', branch: 'fe'

group :development, :test do
  gem 'simplecov', '>= 0.3.5', require: false
  gem 'test-unit'
  gem 'factory_girl_rails'
  gem 'guard-test'
  gem 'spork-rails'#, '~> 3.2.0'
  gem 'guard-spork'
  gem 'spork-testunit'
  gem 'mocha'
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-stack_explorer'
  gem 'pry-debugger'
  #gem 'better_errors'
  #gem 'binding_of_caller'
end
